//
// UIColor+Crayola.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
// Created by Mihaela Mihaljević Jakić
// Color codes source: http://en.wikipedia.org/wiki/List_of_Crayola_crayon_colors
//
//

#import "UIColor+Crayola.h"

@implementation UIColor (Crayola)

+(UIColor *)crayola_Almond_Color 
{
	return [UIColor colorWithRed:239/255.0 green:222/255.0 blue:205/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_AntiqueBrass_Color 
{
	return [UIColor colorWithRed:205/255.0 green:149/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Apricot_Color 
{
	return [UIColor colorWithRed:253/255.0 green:217/255.0 blue:181/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Aquamarine_Color 
{
	return [UIColor colorWithRed:120/255.0 green:219/255.0 blue:226/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Asparagus_Color 
{
	return [UIColor colorWithRed:135/255.0 green:169/255.0 blue:107/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_AtomicTangerine_Color 
{
	return [UIColor colorWithRed:255/255.0 green:164/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BananaMania_Color 
{
	return [UIColor colorWithRed:250/255.0 green:231/255.0 blue:181/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Beaver_Color 
{
	return [UIColor colorWithRed:159/255.0 green:129/255.0 blue:112/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Bittersweet_Color 
{
	return [UIColor colorWithRed:253/255.0 green:124/255.0 blue:110/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Black_Color 
{
	return [UIColor colorWithRed:0/255.0 green:0/255.0 blue:0/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BlizzardBlue_Color 
{
	return [UIColor colorWithRed:172/255.0 green:229/255.0 blue:238/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Blue_Color 
{
	return [UIColor colorWithRed:31/255.0 green:117/255.0 blue:254/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BlueBell_Color 
{
	return [UIColor colorWithRed:162/255.0 green:162/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BlueGray_Color 
{
	return [UIColor colorWithRed:102/255.0 green:153/255.0 blue:204/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BlueGreen_Color 
{
	return [UIColor colorWithRed:13/255.0 green:152/255.0 blue:186/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BlueViolet_Color 
{
	return [UIColor colorWithRed:115/255.0 green:102/255.0 blue:189/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Blush_Color 
{
	return [UIColor colorWithRed:222/255.0 green:93/255.0 blue:131/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BrickRed_Color 
{
	return [UIColor colorWithRed:203/255.0 green:65/255.0 blue:84/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Brown_Color 
{
	return [UIColor colorWithRed:180/255.0 green:103/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BurntOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:127/255.0 blue:73/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_BurntSienna_Color 
{
	return [UIColor colorWithRed:234/255.0 green:126/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_CadetBlue_Color 
{
	return [UIColor colorWithRed:176/255.0 green:183/255.0 blue:198/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Canary_Color 
{
	return [UIColor colorWithRed:255/255.0 green:255/255.0 blue:153/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_CaribbeanGreen_Color 
{
	return [UIColor colorWithRed:0/255.0 green:204/255.0 blue:153/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_CarnationPink_Color 
{
	return [UIColor colorWithRed:255/255.0 green:170/255.0 blue:204/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Cerise_Color 
{
	return [UIColor colorWithRed:221/255.0 green:68/255.0 blue:146/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Cerulean_Color 
{
	return [UIColor colorWithRed:29/255.0 green:172/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Chestnut_Color 
{
	return [UIColor colorWithRed:188/255.0 green:93/255.0 blue:88/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Copper_Color 
{
	return [UIColor colorWithRed:221/255.0 green:148/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Cornflower_Color 
{
	return [UIColor colorWithRed:154/255.0 green:206/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_CottonCandy_Color 
{
	return [UIColor colorWithRed:255/255.0 green:188/255.0 blue:217/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Dandelion_Color 
{
	return [UIColor colorWithRed:253/255.0 green:219/255.0 blue:109/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Denim_Color 
{
	return [UIColor colorWithRed:43/255.0 green:108/255.0 blue:196/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_DesertSand_Color 
{
	return [UIColor colorWithRed:239/255.0 green:205/255.0 blue:184/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Eggplant_Color 
{
	return [UIColor colorWithRed:110/255.0 green:81/255.0 blue:96/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_ElectricLime_Color 
{
	return [UIColor colorWithRed:206/255.0 green:255/255.0 blue:29/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Fern_Color 
{
	return [UIColor colorWithRed:113/255.0 green:188/255.0 blue:120/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_ForestGreen_Color 
{
	return [UIColor colorWithRed:109/255.0 green:174/255.0 blue:129/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Fuchsia_Color 
{
	return [UIColor colorWithRed:195/255.0 green:100/255.0 blue:197/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_FuzzyWuzzy_Color 
{
	return [UIColor colorWithRed:204/255.0 green:102/255.0 blue:102/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Gold_Color 
{
	return [UIColor colorWithRed:231/255.0 green:198/255.0 blue:151/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Goldenrod_Color 
{
	return [UIColor colorWithRed:252/255.0 green:217/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_GrannySmithApple_Color 
{
	return [UIColor colorWithRed:168/255.0 green:228/255.0 blue:160/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Gray_Color 
{
	return [UIColor colorWithRed:149/255.0 green:145/255.0 blue:140/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Green_Color 
{
	return [UIColor colorWithRed:28/255.0 green:172/255.0 blue:120/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_GreenBlue_Color 
{
	return [UIColor colorWithRed:17/255.0 green:100/255.0 blue:180/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_GreenYellow_Color 
{
	return [UIColor colorWithRed:240/255.0 green:232/255.0 blue:145/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_HotMagenta_Color 
{
	return [UIColor colorWithRed:255/255.0 green:29/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Inchworm_Color 
{
	return [UIColor colorWithRed:178/255.0 green:236/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Indigo_Color 
{
	return [UIColor colorWithRed:93/255.0 green:118/255.0 blue:203/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_JazzberryJam_Color 
{
	return [UIColor colorWithRed:202/255.0 green:55/255.0 blue:103/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_JungleGreen_Color 
{
	return [UIColor colorWithRed:59/255.0 green:176/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_LaserLemon_Color 
{
	return [UIColor colorWithRed:254/255.0 green:254/255.0 blue:34/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Lavender_Color 
{
	return [UIColor colorWithRed:252/255.0 green:180/255.0 blue:213/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_LemonYellow_Color 
{
	return [UIColor colorWithRed:255/255.0 green:244/255.0 blue:79/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_MacaroniandCheese_Color 
{
	return [UIColor colorWithRed:255/255.0 green:189/255.0 blue:136/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Magenta_Color 
{
	return [UIColor colorWithRed:246/255.0 green:100/255.0 blue:175/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_MagicMint_Color 
{
	return [UIColor colorWithRed:170/255.0 green:240/255.0 blue:209/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Mahogany_Color 
{
	return [UIColor colorWithRed:205/255.0 green:74/255.0 blue:76/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Maize_Color 
{
	return [UIColor colorWithRed:237/255.0 green:209/255.0 blue:156/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Manatee_Color 
{
	return [UIColor colorWithRed:151/255.0 green:154/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_MangoTango_Color 
{
	return [UIColor colorWithRed:255/255.0 green:130/255.0 blue:67/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Maroon_Color 
{
	return [UIColor colorWithRed:200/255.0 green:56/255.0 blue:90/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Mauvelous_Color 
{
	return [UIColor colorWithRed:239/255.0 green:152/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Melon_Color 
{
	return [UIColor colorWithRed:253/255.0 green:188/255.0 blue:180/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_MidnightBlue_Color 
{
	return [UIColor colorWithRed:26/255.0 green:72/255.0 blue:118/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_MountainMeadow_Color 
{
	return [UIColor colorWithRed:48/255.0 green:186/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Mulberry_Color 
{
	return [UIColor colorWithRed:197/255.0 green:75/255.0 blue:140/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_NavyBlue_Color 
{
	return [UIColor colorWithRed:25/255.0 green:116/255.0 blue:210/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_NeonCarrot_Color 
{
	return [UIColor colorWithRed:255/255.0 green:163/255.0 blue:67/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_OliveGreen_Color 
{
	return [UIColor colorWithRed:186/255.0 green:184/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Orange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:117/255.0 blue:56/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_OrangeRed_Color 
{
	return [UIColor colorWithRed:255/255.0 green:43/255.0 blue:43/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_OrangeYellow_Color 
{
	return [UIColor colorWithRed:248/255.0 green:213/255.0 blue:104/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Orchid_Color 
{
	return [UIColor colorWithRed:230/255.0 green:168/255.0 blue:215/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_OuterSpace_Color 
{
	return [UIColor colorWithRed:65/255.0 green:74/255.0 blue:76/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_OutrageousOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:110/255.0 blue:74/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PacificBlue_Color 
{
	return [UIColor colorWithRed:28/255.0 green:169/255.0 blue:201/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Peach_Color 
{
	return [UIColor colorWithRed:255/255.0 green:207/255.0 blue:171/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Periwinkle_Color 
{
	return [UIColor colorWithRed:197/255.0 green:208/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PiggyPink_Color 
{
	return [UIColor colorWithRed:253/255.0 green:221/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PineGreen_Color 
{
	return [UIColor colorWithRed:21/255.0 green:128/255.0 blue:120/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PinkFlamingo_Color 
{
	return [UIColor colorWithRed:252/255.0 green:116/255.0 blue:253/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PinkSherbert_Color 
{
	return [UIColor colorWithRed:247/255.0 green:143/255.0 blue:167/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Plum_Color 
{
	return [UIColor colorWithRed:142/255.0 green:69/255.0 blue:133/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PurpleHeart_Color 
{
	return [UIColor colorWithRed:116/255.0 green:66/255.0 blue:200/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PurpleMountainsMajesty_Color 
{
	return [UIColor colorWithRed:157/255.0 green:129/255.0 blue:186/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_PurplePizzazz_Color 
{
	return [UIColor colorWithRed:254/255.0 green:78/255.0 blue:218/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RadicalRed_Color 
{
	return [UIColor colorWithRed:255/255.0 green:73/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RawSienna_Color 
{
	return [UIColor colorWithRed:214/255.0 green:138/255.0 blue:89/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RawUmber_Color 
{
	return [UIColor colorWithRed:113/255.0 green:75/255.0 blue:35/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RazzleDazzleRose_Color 
{
	return [UIColor colorWithRed:255/255.0 green:72/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Razzmatazz_Color 
{
	return [UIColor colorWithRed:227/255.0 green:37/255.0 blue:107/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Red_Color 
{
	return [UIColor colorWithRed:238/255.0 green:32/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RedOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:83/255.0 blue:73/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RedViolet_Color 
{
	return [UIColor colorWithRed:192/255.0 green:68/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RobinsEggBlue_Color 
{
	return [UIColor colorWithRed:31/255.0 green:206/255.0 blue:203/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_RoyalPurple_Color 
{
	return [UIColor colorWithRed:120/255.0 green:81/255.0 blue:169/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Salmon_Color 
{
	return [UIColor colorWithRed:255/255.0 green:155/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Scarlet_Color 
{
	return [UIColor colorWithRed:252/255.0 green:40/255.0 blue:71/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_ScreaminGreen_Color 
{
	return [UIColor colorWithRed:118/255.0 green:255/255.0 blue:122/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_SeaGreen_Color 
{
	return [UIColor colorWithRed:147/255.0 green:223/255.0 blue:184/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Sepia_Color 
{
	return [UIColor colorWithRed:165/255.0 green:105/255.0 blue:79/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Shadow_Color 
{
	return [UIColor colorWithRed:138/255.0 green:121/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Shamrock_Color 
{
	return [UIColor colorWithRed:69/255.0 green:206/255.0 blue:162/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_ShockingPink_Color 
{
	return [UIColor colorWithRed:251/255.0 green:126/255.0 blue:253/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Silver_Color 
{
	return [UIColor colorWithRed:205/255.0 green:197/255.0 blue:194/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_SkyBlue_Color 
{
	return [UIColor colorWithRed:128/255.0 green:218/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_SpringGreen_Color 
{
	return [UIColor colorWithRed:236/255.0 green:234/255.0 blue:190/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Sunglow_Color 
{
	return [UIColor colorWithRed:255/255.0 green:207/255.0 blue:72/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_SunsetOrange_Color 
{
	return [UIColor colorWithRed:253/255.0 green:94/255.0 blue:83/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Tan_Color 
{
	return [UIColor colorWithRed:250/255.0 green:167/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_TealBlue_Color 
{
	return [UIColor colorWithRed:24/255.0 green:167/255.0 blue:181/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Thistle_Color 
{
	return [UIColor colorWithRed:235/255.0 green:199/255.0 blue:223/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_TickleMePink_Color 
{
	return [UIColor colorWithRed:252/255.0 green:137/255.0 blue:172/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Timberwolf_Color 
{
	return [UIColor colorWithRed:219/255.0 green:215/255.0 blue:210/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_TropicalRainForest_Color 
{
	return [UIColor colorWithRed:23/255.0 green:128/255.0 blue:109/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Tumbleweed_Color 
{
	return [UIColor colorWithRed:222/255.0 green:170/255.0 blue:136/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_TurquoiseBlue_Color 
{
	return [UIColor colorWithRed:119/255.0 green:221/255.0 blue:231/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_UnmellowYellow_Color 
{
	return [UIColor colorWithRed:255/255.0 green:255/255.0 blue:102/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_VioletBlue_Color 
{
	return [UIColor colorWithRed:50/255.0 green:74/255.0 blue:178/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_VioletPurple_Color 
{
	return [UIColor colorWithRed:146/255.0 green:110/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_VioletRed_Color 
{
	return [UIColor colorWithRed:247/255.0 green:83/255.0 blue:148/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_VividTangerine_Color 
{
	return [UIColor colorWithRed:255/255.0 green:160/255.0 blue:137/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_VividViolet_Color 
{
	return [UIColor colorWithRed:143/255.0 green:80/255.0 blue:157/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_White_Color 
{
	return [UIColor colorWithRed:255/255.0 green:255/255.0 blue:255/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_WildBlueYonder_Color 
{
	return [UIColor colorWithRed:162/255.0 green:173/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_WildStrawberry_Color 
{
	return [UIColor colorWithRed:255/255.0 green:67/255.0 blue:164/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_WildWatermelon_Color 
{
	return [UIColor colorWithRed:252/255.0 green:108/255.0 blue:133/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Wisteria_Color 
{
	return [UIColor colorWithRed:205/255.0 green:164/255.0 blue:222/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_Yellow_Color 
{
	return [UIColor colorWithRed:252/255.0 green:232/255.0 blue:131/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_YellowGreen_Color 
{
	return [UIColor colorWithRed:197/255.0 green:227/255.0 blue:132/255.0 alpha:255/255.0];
};

+(UIColor *)crayola_YellowOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:174/255.0 blue:66/255.0 alpha:255/255.0];
};

@end